/**
 * Multi-Page Shop Schema (v12)
 *
 * EXTENDS the v11 single-page schema to support full multi-page shops
 * rendered through marketplace (e.g., basketplace.co/stores/{slug})
 *
 * Generated by Agent 01 v12 — Multi-Page Shop Builder
 *
 * Breaking change from v11:
 * - Single `blocks` array → `pages[]` array (each with own blocks)
 * - Added `globalHeader` + `globalFooter` (rendered on every page)
 * - Per-page `metadata` overrides root metadata
 */

import type {
  DesignFamilyCode,
  LegacyThemeVariant,
  ThemeVariant,
} from "@/lib/landing/families";

// Re-export for convenience
export type { ThemeVariant };
export type DesignFamily = DesignFamilyCode;

// ============================================================================
// Page Metadata
// ============================================================================

export interface PageMetadata {
  title: string;
  description: string;
  favicon?: {
    imageUrl: string;
    altText?: string;
    size?: string;
  };
  ogImage?: {
    imageUrl: string;
    altText: string;
    width?: number;
    height?: number;
  };
  ogTitle?: string;
  ogDescription?: string;
  twitterCard?: "summary" | "summary_large_image";
  canonicalUrl?: string;
  language?: string;
  themeColor?: string;
}

// ============================================================================
// Global Header (rendered on every page)
// ============================================================================

export interface GlobalHeader {
  logo: {
    imageUrl: string;
    altText: string;
    linkTo?: string;
    brandText?: string;
    size?: "sm" | "md" | "lg";
  };
  nav: Array<{
    text: string;
    href: string;
    isExternal?: boolean;
  }>;
  showCart?: boolean;
  showSearch?: boolean;
  sticky?: boolean;
  banner?: {
    text: string;
    ctaText?: string;
    ctaLink?: string;
    dismissible?: boolean;
  };
}

// ============================================================================
// Global Footer (rendered on every page)
// ============================================================================

export interface GlobalFooter {
  brand?: {
    name: string;
    logoUrl?: string;
    logoAlt?: string;
    description?: string;
  };
  columns?: Array<{
    title: string;
    links: Array<{ text: string; href: string }>;
  }>;
  contact?: {
    email?: string;
    phone?: string;
    address?: string;
    lineId?: string;
  };
  socialLinks?: Array<{
    platform: "facebook" | "instagram" | "tiktok" | "youtube" | "twitter" | "line";
    href: string;
  }>;
  copyright?: string;
  newsletter?: {
    title: string;
    placeholder: string;
    ctaText: string;
  };
}

// ============================================================================
// Block (reuses existing structure from BlockRenderer.tsx)
// ============================================================================

export type Block = {
  blockType: string;
  type?: string;
  content: Record<string, unknown>;
};

// ============================================================================
// Single Page (now part of multi-page schema)
// ============================================================================

export interface ShopPage {
  /** URL slug — used in routing (e.g., "products" → /stores/{slug}/products) */
  slug: string;

  /** Mark as homepage — rendered at /stores/{slug} (no slug suffix) */
  isHomepage?: boolean;

  /** Optional metadata override for this specific page */
  metadata?: Partial<PageMetadata>;

  /** Blocks rendered between header and footer */
  blocks: Block[];
}

// ============================================================================
// Multi-Page Shop Schema (root)
// ============================================================================

export interface MultiPageShopSchema {
  /** Schema version — for migration compatibility */
  schemaVersion: "12";

  /** Site-wide metadata (defaults; pages can override) */
  metadata: PageMetadata;

  /** Design system */
  designFamily: DesignFamily;

  /** Persistent header rendered on every page */
  globalHeader: GlobalHeader;

  /** Persistent footer rendered on every page */
  globalFooter: GlobalFooter;

  /** Array of pages in this shop */
  pages: ShopPage[];
}

// ============================================================================
// Backward compat: v11 single-page schema (for migration)
// ============================================================================

export interface SinglePageSchema {
  metadata?: Partial<PageMetadata>;
  designFamily?: DesignFamily;
  /** Legacy v2 field */
  themeVariant?: LegacyThemeVariant;
  blocks: Block[];
}
