/**
 * Marketplace Store Templates — Type System
 *
 * A Template is a config that lists which Blocks to render in what order.
 * Adding a template = new config (no new code).
 * Adding a block type = new component + register in renderer.
 */

// ============================================================================
// Block primitives
// ============================================================================

export type BlockType =
  | 'hero'
  | 'store-header'
  | 'nav'
  | 'product'
  | 'collection'
  | 'category'
  | 'swatch'
  | 'live'
  | 'video-feed'
  | 'compare'
  | 'pricing-tier'
  | 'countdown'
  | 'drop-calendar'
  | 'story'
  | 'sticky';

export interface Block {
  type: BlockType;
  variant: string;
  data?: Record<string, unknown>;
  /** Block instance ID for editing/reordering. Auto-generated by default. */
  id?: string;
}

// ============================================================================
// Theme tokens
// ============================================================================

export interface ThemeTokens {
  colors: {
    primary: string;
    accent: string;
    surface: string;
    text: string;
  };
  typography: {
    titleScale: 'compact' | 'default' | 'editorial';
    fontFamily: 'default' | 'serif' | 'display';
  };
  spacing: 'compact' | 'default' | 'airy';
  radius: 'sharp' | 'default' | 'round';
}

// ============================================================================
// Template configuration
// ============================================================================

export type TemplateGroup =
  | 'trust'
  | 'fashion-beauty'
  | 'electronics-tech'
  | 'lifestyle'
  | 'community'
  | 'business-model'
  | 'specialty';

export type TemplateId =
  | 'classic'
  | 'official-brand'
  | 'premium-luxury'
  | 'lookbook'
  | 'beauty-swatch'
  | 'boutique'
  | 'catalog-dense'
  | 'tech-compare'
  | 'single-product'
  | 'home-living'
  | 'sport-active'
  | 'kids-toys'
  | 'live-commerce'
  | 'video-feed'
  | 'storyteller'
  | 'wholesale-b2b'
  | 'flash-deal'
  | 'subscription'
  | 'handmade'
  | 'vintage';

export type DesktopPattern = 'A' | 'B' | 'C' | 'D';

export interface BehaviorFlags {
  bottomNav?: 'visible' | 'hidden';
  stickyCart?: boolean;
  stickyCTA?: 'buy-now' | 'add-to-cart' | 'none';
  coverHidden?: boolean;
  searchInTopBar?: boolean;
  showTabs?: boolean;
  productGridDensity?: 'standard' | 'dense';
  hideRatingsCount?: boolean;
  liveBlock?: 'visible' | 'hidden';
  swatchRow?: 'visible' | 'hidden';
  categoryTilesColored?: boolean;
  performanceBadges?: 'visible' | 'hidden';
  countdownBanner?: 'visible' | 'hidden';
  stockIndicators?: 'visible' | 'hidden';
  dropCalendar?: 'visible' | 'hidden';
  recurringPlan?: 'enabled' | 'disabled';
  makerPortrait?: 'visible' | 'hidden';
  conditionBadges?: 'visible' | 'hidden';
  uniqueItemMode?: boolean;
  storyBlock?: 'inline-visible' | 'hidden';
  b2bMode?: boolean;
  singleProductMode?: boolean;
}

export interface GatingConfig {
  requiresKYC?: 'basic' | 'brand-verified' | 'business-verified';
  requiresModule?: ('live-commerce' | 'video-content' | 'subscription')[];
}

export interface CustomizableConfig {
  canReorder: boolean;
  canHideBlocks: BlockType[];
  canAddBlocks: BlockType[];
}

export interface Template {
  id: TemplateId;
  name: string;
  description: string;
  group: TemplateGroup;
  mobileBlocks: Block[];
  desktopPattern: DesktopPattern;
  desktopBlocks?: Block[];
  theme: ThemeTokens;
  behavior: BehaviorFlags;
  gating: GatingConfig;
  customizable: CustomizableConfig;
}

// ============================================================================
// Store data
// ============================================================================

export interface Store {
  id: string;
  slug: string;
  name: string;
  description?: string;
  niche: string;
  branding: StoreBranding;
  templateId: TemplateId;
  themeOverrides?: Partial<ThemeTokens>;
  badges?: StoreBadges;
  rating: number;
  followers: number;
  collections: Collection[];
  products: Product[];
  liveStream?: LiveStreamInfo;
}

export interface StoreBranding {
  logoUrl?: string;
  bannerUrl?: string;
  portraitUrl?: string;
  videoUrl?: string;
  colors: {
    primary: string;
    accent: string;
    surface: string;
    text: string;
  };
}

export interface StoreBadges {
  official?: boolean;
  b2b?: boolean;
  verified?: boolean;
}

export interface Collection {
  id: string;
  name: string;
  description?: string;
  imageUrl?: string;
  productIds: string[];
  featured?: boolean;
  order?: number;
}

export interface Product {
  id: string;
  storeId: string;
  title: string;
  description?: string;
  price: number;
  originalPrice?: number;
  currency: 'THB';
  images: string[];
  thumbnailUrl: string;
  rating: number;
  reviewCount: number;
  soldCount: number;
  inStock: boolean;
  stockLeft?: number;
  variants?: ProductVariant[];
  attributes?: Record<string, string>;
  conditionLabel?: 'new' | 'like-new' | 'good' | 'fair' | 'refurbished';
  badges?: ('hot' | 'new' | 'limited' | 'pro' | 'official')[];
  pricingTiers?: PricingTier[];
}

export interface ProductVariant {
  id: string;
  name: string;
  type: 'color' | 'size' | 'material' | 'style';
  swatch?: string;
  available: boolean;
}

export interface PricingTier {
  minQuantity: number;
  pricePerUnit: number;
}

export interface LiveStreamInfo {
  isLive: boolean;
  streamUrl?: string;
  thumbnailUrl?: string;
  viewerCount: number;
  hostName: string;
  hostAvatarUrl?: string;
  replays?: { id: string; thumbnailUrl: string; title: string; duration: number }[];
}
